[platformio]
default_envs = esp32c3

[env]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:esp32c3]
platform = espressif32@7.1.3
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

[env:native]
platform = native
lib_ignore = drivers_esp32
test_framework = unity

[env:native_cobertura]
extends = env:native
build_flags =
  ${env.build_flags}
  -O0
  --coverage
extra_scripts = post:cobertura_link.py
